### ISSUE TITLE
Interface Design - UI/UX

### ISSUE THREAD

**Issue by tolstenko** [InfiniBrains/DicomViewer#5]
Design how the interface will look like. Here go some references:
- Radiant viewer - smallest viewer, and still robust
- OHIF - https://github.com/OHIF/Viewers
- Osirix - more robust
- 3d slicer https://www.slicer.org is the more reliable in terms of extending via python, editing tool and manipulating medical images
- mango https://mangoviewer.com/mango.html is the most straight to the point viewer
- POSTDICOM
- Horos

Read more here. https://www.postdicom.com/en/blog/top-25-free-dicom-viewers

**Comment by gusg21** [comment]
UI Notes/Ideas: https://docs.google.com/presentation/d/1eLZnDyCp7O5Gi2phxCkNMsYSwEowYIZiUyE0njKeKaI/edit#slide=id.p

**Comment by gusg21** [comment]
A basic "shell" of the design has been designed and executed, functionality definitely still needs to be added though.

**Comment by tolstenko** [comment]
Suggestion on how to render https://www.youtube.com/watch?v=tJMGe3FMTk0 this would be the simplest approach. Another approach would be to change the plane's orientation as seen here https://www.youtube.com/watch?v=GqpQ9N6jFWQ Try the easiest approach first and then move to the harder. 

You can mock a voxel data using noise functions via simplex noise3d to generate a 3d matrix of voxels while #6 is not ready @dillondrum70 .
